name = "enterprise-pos-frontend"
compatibility_date = "2024-01-01"

# Production environment
[env.production]
name = "enterprise-pos-frontend"

# Staging environment  
[env.staging]
name = "enterprise-pos-frontend-staging"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Pages configuration
[pages]
build_output_dir = "dist" 