# Cloudflare Pages Configuration
name = "enterprise-pos-frontend"
compatibility_date = "2024-12-01"

# Pages specific configuration
pages_build_output_dir = "dist"

[build]
command = "npm run build"
cwd = "frontend"

[build.environment_variables]
NODE_VERSION = "18"
NPM_VERSION = "8"

# Deployment settings
[env.production]
name = "enterprise-pos-frontend"

[env.preview]
name = "enterprise-pos-frontend-preview"

# Custom domains (optional)
# [env.production.route]
# pattern = "pos.yourcompany.com"
# zone_name = "yourcompany.com"