name = "cloudflare-enterprise-pos-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
node_compat = true

# Pages build output directory (for Pages integration)
pages_build_output_dir = "../frontend/dist"

[vars]
ENVIRONMENT = "development"

[env.production]
name = "cloudflare-enterprise-pos-api-prod"

[env.production.vars]
ENVIRONMENT = "production"
