name = "enterprise-pos-backend"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "enterprise-pos-backend"

[env.staging]
name = "enterprise-pos-backend-staging"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "enterprise-pos-db"
database_id = "aecff177-2deb-4bda-834a-17e4b750441d"

# KV Store Configuration
[[kv_namespaces]]
binding = "CACHE"
id = "46b31b2c6ca449aaa3114d0ebb4fe645"

# R2 Storage Configuration (Enable R2 in Cloudflare Dashboard first)
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "enterprise-pos-files"

# AI Binding Configuration
[ai]
binding = "AI"

# Environment Variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
ENCRYPTION_KEY = "your-32-char-encryption-key-here!!"
ADMIN_EMAIL = "admin@yourcompany.com"
COMPANY_NAME = "Your Company Name"
API_VERSION = "v1"
MAX_FILE_SIZE = "10485760"
SESSION_TIMEOUT = "86400"

# Limits Configuration
[limits]
cpu_ms = 30000