name = "enterprise-pos-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "enterprise-pos-backend"

[env.staging]
name = "enterprise-pos-backend-staging"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "enterprise-pos-db"
database_id = "your-database-id-here"

# KV Store Configuration
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# R2 Storage Configuration
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "enterprise-pos-files"
preview_bucket_name = "enterprise-pos-files-preview"

# AI Binding Configuration
[ai]
binding = "AI"

# Environment Variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
ENCRYPTION_KEY = "your-32-char-encryption-key-here!!"
ADMIN_EMAIL = "admin@yourcompany.com"
COMPANY_NAME = "Your Company Name"
API_VERSION = "v1"
MAX_FILE_SIZE = "10485760"
SESSION_TIMEOUT = "86400"

# WebSocket Configuration
[websocket]
max_connections = 1000

# Rate Limiting
[limits]
cpu_ms = 30000
memory_mb = 128